services:
  twl-postgres:
    image: postgres:16-alpine
    container_name: twl-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: twl_db
      POSTGRES_USER: twl
      POSTGRES_PASSWORD: twladmin
    ports:
      - "55432:5432"
    volumes:
      - twl-postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  twl-postgres-data:
